export const countryList = [
  {
    dialCode: "+93",
    countryCode: "AF",
    name: "Afghanistan",
    flag: "🇦🇫",
  },
  {
    dialCode: "+358",
    countryCode: "AX",
    name: "Åland Islands",
    flag: "🇦🇽",
  },
  {
    dialCode: "+355",
    countryCode: "AL",
    name: "Albania",
    flag: "🇦🇱",
  },
  {
    dialCode: "+213",
    countryCode: "DZ",
    name: "Algeria",
    flag: "🇩🇿",
  },
  {
    dialCode: "+1 684",
    countryCode: "AS",
    name: "American Samoa",
    flag: "🇦🇸",
  },
  {
    dialCode: "+376",
    countryCode: "AD",
    name: "Andorra",
    flag: "🇦🇩",
  },
  {
    dialCode: "+244",
    countryCode: "AO",
    name: "Angola",
    flag: "🇦🇴",
  },
  {
    dialCode: "+1 264",
    countryCode: "AI",
    name: "Anguilla",
    flag: "🇦🇮",
  },
  {
    dialCode: "+672",
    countryCode: "AQ",
    name: "Antarctica",
    flag: "🇦🇶",
  },
  {
    dialCode: "+1 268",
    countryCode: "AG",
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
  },
  {
    dialCode: "+54",
    countryCode: "AR",
    name: "Argentina",
    flag: "🇦🇷",
  },
  {
    dialCode: "+374",
    countryCode: "AM",
    name: "Armenia",
    flag: "🇦🇲",
  },
  {
    dialCode: "+297",
    countryCode: "AW",
    name: "Aruba",
    flag: "🇦🇼",
  },
  {
    dialCode: "+61",
    countryCode: "AU",
    name: "Australia",
    flag: "🇦🇺",
  },
  {
    dialCode: "+43",
    countryCode: "AT",
    name: "Austria",
    flag: "🇦🇹",
  },
  {
    dialCode: "+994",
    countryCode: "AZ",
    name: "Azerbaijan",
    flag: "🇦🇿",
  },
  {
    dialCode: "+1 242",
    countryCode: "BS",
    name: "Bahamas",
    flag: "🇧🇸",
  },
  {
    dialCode: "+973",
    countryCode: "BH",
    name: "Bahrain",
    flag: "🇧🇭",
  },
  {
    dialCode: "+880",
    countryCode: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
  },
  {
    dialCode: "+1 246",
    countryCode: "BB",
    name: "Barbados",
    flag: "🇧🇧",
  },
  {
    dialCode: "+375",
    countryCode: "BY",
    name: "Belarus",
    flag: "🇧🇾",
  },
  {
    dialCode: "+32",
    countryCode: "BE",
    name: "Belgium",
    flag: "🇧🇪",
  },
  {
    dialCode: "+501",
    countryCode: "BZ",
    name: "Belize",
    flag: "🇧🇿",
  },
  {
    dialCode: "+229",
    countryCode: "BJ",
    name: "Benin",
    flag: "🇧🇯",
  },
  {
    dialCode: "+1 441",
    countryCode: "BM",
    name: "Bermuda",
    flag: "🇧🇲",
  },
  {
    dialCode: "+975",
    countryCode: "BT",
    name: "Bhutan",
    flag: "🇧🇹",
  },
  {
    dialCode: "+591",
    countryCode: "BO",
    name: "Bolivia",
    flag: "🇧🇴",
  },
  {
    dialCode: "+387",
    countryCode: "BA",
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
  },
  {
    dialCode: "+267",
    countryCode: "BW",
    name: "Botswana",
    flag: "🇧🇼",
  },
  {
    dialCode: "+55",
    countryCode: "BR",
    name: "Brazil",
    flag: "🇧🇷",
  },
  {
    dialCode: "+246",
    countryCode: "IO",
    name: "British Indian Ocean Territory",
    flag: "🇮🇴",
  },
  {
    dialCode: "+1 284",
    countryCode: "VG",
    name: "British Virgin Islands",
    flag: "🇻🇬",
  },
  {
    dialCode: "+673",
    countryCode: "BN",
    name: "Brunei",
    flag: "🇧🇳",
  },
  {
    dialCode: "+359",
    countryCode: "BG",
    name: "Bulgaria",
    flag: "🇧🇬",
  },
  {
    dialCode: "+226",
    countryCode: "BF",
    name: "Burkina Faso",
    flag: "🇧🇫",
  },
  {
    dialCode: "+257",
    countryCode: "BI",
    name: "Burundi",
    flag: "🇧🇮",
  },
  {
    dialCode: "+855",
    countryCode: "KH",
    name: "Cambodia",
    flag: "🇰🇭",
  },
  {
    dialCode: "+237",
    countryCode: "CM",
    name: "Cameroon",
    flag: "🇨🇲",
  },
  {
    dialCode: "+1",
    countryCode: "CA",
    name: "Canada",
    flag: "🇨🇦",
  },
  {
    dialCode: "+238",
    countryCode: "CV",
    name: "Cape Verde",
    flag: "🇨🇻",
  },
  {
    dialCode: "+1 345",
    countryCode: "KY",
    name: "Cayman Islands",
    flag: "🇰🇾",
  },
  {
    dialCode: "+236",
    countryCode: "CF",
    name: "Central African Republic",
    flag: "🇨🇫",
  },
  {
    dialCode: "+235",
    countryCode: "TD",
    name: "Chad",
    flag: "🇹🇩",
  },
  {
    dialCode: "+56",
    countryCode: "CL",
    name: "Chile",
    flag: "🇨🇱",
  },
  {
    dialCode: "+86",
    countryCode: "CN",
    name: "China",
    flag: "🇨🇳",
  },
  {
    dialCode: "+61",
    countryCode: "CX",
    name: "Christmas Island",
    flag: "🇨🇽",
  },
  {
    dialCode: "+61",
    countryCode: "CC",
    name: "Cocos (Keeling) Islands",
    flag: "🇨🇨",
  },
  {
    dialCode: "+57",
    countryCode: "CO",
    name: "Colombia",
    flag: "🇨🇴",
  },
  {
    dialCode: "+269",
    countryCode: "KM",
    name: "Comoros",
    flag: "🇰🇲",
  },
  {
    dialCode: "+682",
    countryCode: "CK",
    name: "Cook Islands",
    flag: "🇨🇰",
  },
  {
    dialCode: "+506",
    countryCode: "CR",
    name: "Costa Rica",
    flag: "🇨🇷",
  },
  {
    dialCode: "+385",
    countryCode: "HR",
    name: "Croatia",
    flag: "🇭🇷",
  },
  {
    dialCode: "+53",
    countryCode: "CU",
    name: "Cuba",
    flag: "🇨🇺",
  },
  {
    dialCode: "+599",
    countryCode: "CW",
    name: "Curaçao",
    flag: "🇨🇼",
  },
  {
    dialCode: "+357",
    countryCode: "CY",
    name: "Cyprus",
    flag: "🇨🇾",
  },
  {
    dialCode: "+420",
    countryCode: "CZ",
    name: "Czech Republic",
    flag: "🇨🇿",
  },
  {
    dialCode: "+243",
    countryCode: "CD",
    name: "Democratic Republic of the Congo",
    flag: "🇨🇩",
  },
  {
    dialCode: "+45",
    countryCode: "DK",
    name: "Denmark",
    flag: "🇩🇰",
  },
  {
    dialCode: "+253",
    countryCode: "DJ",
    name: "Djibouti",
    flag: "🇩🇯",
  },
  {
    dialCode: "+1 767",
    countryCode: "DM",
    name: "Dominica",
    flag: "🇩🇲",
  },
  {
    dialCode: "+1 809",
    countryCode: "DO",
    name: "Dominican Republic",
    flag: "🇩🇴",
  },
  {
    dialCode: "+670",
    countryCode: "TL",
    name: "East Timor",
    flag: "🇹🇱",
  },
  {
    dialCode: "+593",
    countryCode: "EC",
    name: "Ecuador",
    flag: "🇪🇨",
  },
  {
    dialCode: "+20",
    countryCode: "EG",
    name: "Egypt",
    flag: "🇪🇬",
  },
  {
    dialCode: "+503",
    countryCode: "SV",
    name: "El Salvador",
    flag: "🇸🇻",
  },
  {
    dialCode: "+240",
    countryCode: "GQ",
    name: "Equatorial Guinea",
    flag: "🇬🇶",
  },
  {
    dialCode: "+291",
    countryCode: "ER",
    name: "Eritrea",
    flag: "🇪🇷",
  },
  {
    dialCode: "+372",
    countryCode: "EE",
    name: "Estonia",
    flag: "🇪🇪",
  },
  {
    dialCode: "+251",
    countryCode: "ET",
    name: "Ethiopia",
    flag: "🇪🇹",
  },
  {
    dialCode: "+500",
    countryCode: "FK",
    name: "Falkland Islands",
    flag: "🇫🇰",
  },
  {
    dialCode: "+298",
    countryCode: "FO",
    name: "Faroe Islands",
    flag: "🇫🇴",
  },
  {
    dialCode: "+679",
    countryCode: "FJ",
    name: "Fiji",
    flag: "🇫🇯",
  },
  {
    dialCode: "+358",
    countryCode: "FI",
    name: "Finland",
    flag: "🇫🇮",
  },
  {
    dialCode: "+33",
    countryCode: "FR",
    name: "France",
    flag: "🇫🇷",
  },
  {
    dialCode: "+594",
    countryCode: "GF",
    name: "French Guiana",
    flag: "🇬🇫",
  },
  {
    dialCode: "+689",
    countryCode: "PF",
    name: "French Polynesia",
    flag: "🇵🇫",
  },
  {
    dialCode: "+241",
    countryCode: "GA",
    name: "Gabon",
    flag: "🇬🇦",
  },
  {
    dialCode: "+220",
    countryCode: "GM",
    name: "Gambia",
    flag: "🇬🇲",
  },
  {
    dialCode: "+995",
    countryCode: "GE",
    name: "Georgia",
    flag: "🇬🇪",
  },
  {
    dialCode: "+49",
    countryCode: "DE",
    name: "Germany",
    flag: "🇩🇪",
  },
  {
    dialCode: "+233",
    countryCode: "GH",
    name: "Ghana",
    flag: "🇬🇭",
  },
  {
    dialCode: "+350",
    countryCode: "GI",
    name: "Gibraltar",
    flag: "🇬🇮",
  },
  {
    dialCode: "+30",
    countryCode: "GR",
    name: "Greece",
    flag: "🇬🇷",
  },
  {
    dialCode: "+299",
    countryCode: "GL",
    name: "Greenland",
    flag: "🇬🇱",
  },
  {
    dialCode: "+1 473",
    countryCode: "GD",
    name: "Grenada",
    flag: "🇬🇩",
  },
  {
    dialCode: "+590",
    countryCode: "GP",
    name: "Guadeloupe",
    flag: "🇬🇵",
  },
  {
    dialCode: "+1 671",
    countryCode: "GU",
    name: "Guam",
    flag: "🇬🇺",
  },
  {
    dialCode: "+502",
    countryCode: "GT",
    name: "Guatemala",
    flag: "🇬🇹",
  },
  {
    dialCode: "+44",
    countryCode: "GG",
    name: "Guernsey",
    flag: "🇬🇬",
  },
  {
    dialCode: "+224",
    countryCode: "GN",
    name: "Guinea",
    flag: "🇬🇳",
  },
  {
    dialCode: "+245",
    countryCode: "GW",
    name: "Guinea-Bissau",
    flag: "🇬🇼",
  },
  {
    dialCode: "+592",
    countryCode: "GY",
    name: "Guyana",
    flag: "🇬🇾",
  },
  {
    dialCode: "+509",
    countryCode: "HT",
    name: "Haiti",
    flag: "🇭🇹",
  },
  {
    dialCode: "+504",
    countryCode: "HN",
    name: "Honduras",
    flag: "🇭🇳",
  },
  {
    dialCode: "+852",
    countryCode: "HK",
    name: "Hong Kong",
    flag: "🇭🇰",
  },
  {
    dialCode: "+36",
    countryCode: "HU",
    name: "Hungary",
    flag: "🇭🇺",
  },
  {
    dialCode: "+354",
    countryCode: "IS",
    name: "Iceland",
    flag: "🇮🇸",
  },
  {
    dialCode: "+91",
    countryCode: "IN",
    name: "India",
    flag: "🇮🇳",
  },
  {
    dialCode: "+62",
    countryCode: "ID",
    name: "Indonesia",
    flag: "🇮🇩",
  },
  {
    dialCode: "+98",
    countryCode: "IR",
    name: "Iran",
    flag: "🇮🇷",
  },
  {
    dialCode: "+964",
    countryCode: "IQ",
    name: "Iraq",
    flag: "🇮🇶",
  },
  {
    dialCode: "+353",
    countryCode: "IE",
    name: "Ireland",
    flag: "🇮🇪",
  },
  {
    dialCode: "+44",
    countryCode: "IM",
    name: "Isle of Man",
    flag: "🇮🇲",
  },
  {
    dialCode: "+972",
    countryCode: "IL",
    name: "Israel",
    flag: "🇮🇱",
  },
  {
    dialCode: "+39",
    countryCode: "IT",
    name: "Italy",
    flag: "🇮🇹",
  },
  {
    dialCode: "+225",
    countryCode: "CI",
    name: "Ivory Coast",
    flag: "🇨🇮",
  },
  {
    dialCode: "+1 876",
    countryCode: "JM",
    name: "Jamaica",
    flag: "🇯🇲",
  },
  {
    dialCode: "+81",
    countryCode: "JP",
    name: "Japan",
    flag: "🇯🇵",
  },
  {
    dialCode: "+44",
    countryCode: "JE",
    name: "Jersey",
    flag: "🇯🇪",
  },
  {
    dialCode: "+962",
    countryCode: "JO",
    name: "Jordan",
    flag: "🇯🇴",
  },
  {
    dialCode: "+7",
    countryCode: "KZ",
    name: "Kazakhstan",
    flag: "🇰🇿",
  },
  {
    dialCode: "+254",
    countryCode: "KE",
    name: "Kenya",
    flag: "🇰🇪",
  },
  {
    dialCode: "+686",
    countryCode: "KI",
    name: "Kiribati",
    flag: "🇰🇮",
  },
  {
    dialCode: "+383",
    countryCode: "XK",
    name: "Kosovo",
    flag: "🇽🇰",
  },
  {
    dialCode: "+965",
    countryCode: "KW",
    name: "Kuwait",
    flag: "🇰🇼",
  },
  {
    dialCode: "+996",
    countryCode: "KG",
    name: "Kyrgyzstan",
    flag: "🇰🇬",
  },
  {
    dialCode: "+856",
    countryCode: "LA",
    name: "Laos",
    flag: "🇱🇦",
  },
  {
    dialCode: "+371",
    countryCode: "LV",
    name: "Latvia",
    flag: "🇱🇻",
  },
  {
    dialCode: "+961",
    countryCode: "LB",
    name: "Lebanon",
    flag: "🇱🇧",
  },
  {
    dialCode: "+266",
    countryCode: "LS",
    name: "Lesotho",
    flag: "🇱🇸",
  },
  {
    dialCode: "+231",
    countryCode: "LR",
    name: "Liberia",
    flag: "🇱🇷",
  },
  {
    dialCode: "+218",
    countryCode: "LY",
    name: "Libya",
    flag: "🇱🇾",
  },
  {
    dialCode: "+423",
    countryCode: "LI",
    name: "Liechtenstein",
    flag: "🇱🇮",
  },
  {
    dialCode: "+370",
    countryCode: "LT",
    name: "Lithuania",
    flag: "🇱🇹",
  },
  {
    dialCode: "+352",
    countryCode: "LU",
    name: "Luxembourg",
    flag: "🇱🇺",
  },
  {
    dialCode: "+853",
    countryCode: "MO",
    name: "Macau",
    flag: "🇲🇴",
  },
  {
    dialCode: "+389",
    countryCode: "MK",
    name: "North Macedonia",
    flag: "🇲🇰",
  },
  {
    dialCode: "+261",
    countryCode: "MG",
    name: "Madagascar",
    flag: "🇲🇬",
  },
  {
    dialCode: "+265",
    countryCode: "MW",
    name: "Malawi",
    flag: "🇲🇼",
  },
  {
    dialCode: "+60",
    countryCode: "MY",
    name: "Malaysia",
    flag: "🇲🇾",
  },
  {
    dialCode: "+960",
    countryCode: "MV",
    name: "Maldives",
    flag: "🇲🇻",
  },
  {
    dialCode: "+223",
    countryCode: "ML",
    name: "Mali",
    flag: "🇲🇱",
  },
  {
    dialCode: "+356",
    countryCode: "MT",
    name: "Malta",
    flag: "🇲🇹",
  },
  {
    dialCode: "+692",
    countryCode: "MH",
    name: "Marshall Islands",
    flag: "🇲🇭",
  },
  {
    dialCode: "+596",
    countryCode: "MQ",
    name: "Martinique",
    flag: "🇲🇶",
  },
  {
    dialCode: "+222",
    countryCode: "MR",
    name: "Mauritania",
    flag: "🇲🇷",
  },
  {
    dialCode: "+230",
    countryCode: "MU",
    name: "Mauritius",
    flag: "🇲🇺",
  },
  {
    dialCode: "+262",
    countryCode: "YT",
    name: "Mayotte",
    flag: "🇾🇹",
  },
  {
    dialCode: "+52",
    countryCode: "MX",
    name: "Mexico",
    flag: "🇲🇽",
  },
  {
    dialCode: "+691",
    countryCode: "FM",
    name: "Micronesia",
    flag: "🇫🇲",
  },
  {
    dialCode: "+373",
    countryCode: "MD",
    name: "Moldova",
    flag: "🇲🇩",
  },
  {
    dialCode: "+377",
    countryCode: "MC",
    name: "Monaco",
    flag: "🇲🇨",
  },
  {
    dialCode: "+976",
    countryCode: "MN",
    name: "Mongolia",
    flag: "🇲🇳",
  },
  {
    dialCode: "+382",
    countryCode: "ME",
    name: "Montenegro",
    flag: "🇲🇪",
  },
  {
    dialCode: "+1 664",
    countryCode: "MS",
    name: "Montserrat",
    flag: "🇲🇸",
  },
  {
    dialCode: "+212",
    countryCode: "MA",
    name: "Morocco",
    flag: "🇲🇦",
  },
  {
    dialCode: "+258",
    countryCode: "MZ",
    name: "Mozambique",
    flag: "🇲🇿",
  },
  {
    dialCode: "+95",
    countryCode: "MM",
    name: "Myanmar",
    flag: "🇲🇲",
  },
  {
    dialCode: "+264",
    countryCode: "NA",
    name: "Namibia",
    flag: "🇳🇦",
  },
  {
    dialCode: "+674",
    countryCode: "NR",
    name: "Nauru",
    flag: "🇳🇷",
  },
  {
    dialCode: "+977",
    countryCode: "NP",
    name: "Nepal",
    flag: "🇳🇵",
  },
  {
    dialCode: "+31",
    countryCode: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
  },
  {
    dialCode: "+687",
    countryCode: "NC",
    name: "New Caledonia",
    flag: "🇳🇨",
  },
  {
    dialCode: "+64",
    countryCode: "NZ",
    name: "New Zealand",
    flag: "🇳🇿",
  },
  {
    dialCode: "+505",
    countryCode: "NI",
    name: "Nicaragua",
    flag: "🇳🇮",
  },
  {
    dialCode: "+227",
    countryCode: "NE",
    name: "Niger",
    flag: "🇳🇪",
  },
  {
    dialCode: "+234",
    countryCode: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
  },
  {
    dialCode: "+683",
    countryCode: "NU",
    name: "Niue",
    flag: "🇳🇺",
  },
  {
    dialCode: "+850",
    countryCode: "KP",
    name: "North Korea",
    flag: "🇰🇵",
  },
  {
    dialCode: "+1 670",
    countryCode: "MP",
    name: "Northern Mariana Islands",
    flag: "🇲🇵",
  },
  {
    dialCode: "+47",
    countryCode: "NO",
    name: "Norway",
    flag: "🇳🇴",
  },
  {
    dialCode: "+968",
    countryCode: "OM",
    name: "Oman",
    flag: "🇴🇲",
  },
  {
    dialCode: "+92",
    countryCode: "PK",
    name: "Pakistan",
    flag: "🇵🇰",
  },
  {
    dialCode: "+680",
    countryCode: "PW",
    name: "Palau",
    flag: "🇵🇼",
  },
  {
    dialCode: "+970",
    countryCode: "PS",
    name: "Palestine",
    flag: "🇵🇸",
  },
  {
    dialCode: "+507",
    countryCode: "PA",
    name: "Panama",
    flag: "🇵🇦",
  },
  {
    dialCode: "+675",
    countryCode: "PG",
    name: "Papua New Guinea",
    flag: "🇵🇬",
  },
  {
    dialCode: "+595",
    countryCode: "PY",
    name: "Paraguay",
    flag: "🇵🇾",
  },
  {
    dialCode: "+51",
    countryCode: "PE",
    name: "Peru",
    flag: "🇵🇪",
  },
  {
    dialCode: "+63",
    countryCode: "PH",
    name: "Philippines",
    flag: "🇵🇭",
  },
  {
    dialCode: "+48",
    countryCode: "PL",
    name: "Poland",
    flag: "🇵🇱",
  },
  {
    dialCode: "+351",
    countryCode: "PT",
    name: "Portugal",
    flag: "🇵🇹",
  },
  {
    dialCode: "+1 787",
    countryCode: "PR",
    name: "Puerto Rico",
    flag: "🇵🇷",
  },
  {
    dialCode: "+974",
    countryCode: "QA",
    name: "Qatar",
    flag: "🇶🇦",
  },
  {
    dialCode: "+242",
    countryCode: "CG",
    name: "Republic of the Congo",
    flag: "🇨🇬",
  },
  {
    dialCode: "+40",
    countryCode: "RO",
    name: "Romania",
    flag: "🇷🇴",
  },
  {
    dialCode: "+7",
    countryCode: "RU",
    name: "Russia",
    flag: "🇷🇺",
  },
  {
    dialCode: "+250",
    countryCode: "RW",
    name: "Rwanda",
    flag: "🇷🇼",
  },
  {
    dialCode: "+590",
    countryCode: "BL",
    name: "Saint Barthélemy",
    flag: "🇧🇱",
  },
  {
    dialCode: "+290",
    countryCode: "SH",
    name: "Saint Helena",
    flag: "🇸🇭",
  },
  {
    dialCode: "+1 869",
    countryCode: "KN",
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
  },
  {
    dialCode: "+1 758",
    countryCode: "LC",
    name: "Saint Lucia",
    flag: "🇱🇨",
  },
  {
    dialCode: "+590",
    countryCode: "MF",
    name: "Saint Martin",
    flag: "🇲🇫",
  },
  {
    dialCode: "+508",
    countryCode: "PM",
    name: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
  },
  {
    dialCode: "+1 784",
    countryCode: "VC",
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
  },
  {
    dialCode: "+685",
    countryCode: "WS",
    name: "Samoa",
    flag: "🇼🇸",
  },
  {
    dialCode: "+378",
    countryCode: "SM",
    name: "San Marino",
    flag: "🇸🇲",
  },
  {
    dialCode: "+239",
    countryCode: "ST",
    name: "São Tomé and Príncipe",
    flag: "🇸🇹",
  },
  {
    dialCode: "+966",
    countryCode: "SA",
    name: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    dialCode: "+221",
    countryCode: "SN",
    name: "Senegal",
    flag: "🇸🇳",
  },
  {
    dialCode: "+381",
    countryCode: "RS",
    name: "Serbia",
    flag: "🇷🇸",
  },
  {
    dialCode: "+248",
    countryCode: "SC",
    name: "Seychelles",
    flag: "🇸🇨",
  },
  {
    dialCode: "+232",
    countryCode: "SL",
    name: "Sierra Leone",
    flag: "🇸🇱",
  },
  {
    dialCode: "+65",
    countryCode: "SG",
    name: "Singapore",
    flag: "🇸🇬",
  },
  {
    dialCode: "+1 721",
    countryCode: "SX",
    name: "Sint Maarten",
    flag: "🇸🇽",
  },
  {
    dialCode: "+421",
    countryCode: "SK",
    name: "Slovakia",
    flag: "🇸🇰",
  },
  {
    dialCode: "+386",
    countryCode: "SI",
    name: "Slovenia",
    flag: "🇸🇮",
  },
  {
    dialCode: "+677",
    countryCode: "SB",
    name: "Solomon Islands",
    flag: "🇸🇧",
  },
  {
    dialCode: "+252",
    countryCode: "SO",
    name: "Somalia",
    flag: "🇸🇴",
  },
  {
    dialCode: "+27",
    countryCode: "ZA",
    name: "South Africa",
    flag: "🇿🇦",
  },
  {
    dialCode: "+82",
    countryCode: "KR",
    name: "South Korea",
    flag: "🇰🇷",
  },
  {
    dialCode: "+211",
    countryCode: "SS",
    name: "South Sudan",
    flag: "🇸🇸",
  },
  {
    dialCode: "+34",
    countryCode: "ES",
    name: "Spain",
    flag: "🇪🇸",
  },
  {
    dialCode: "+94",
    countryCode: "LK",
    name: "Sri Lanka",
    flag: "🇱🇰",
  },
  {
    dialCode: "+249",
    countryCode: "SD",
    name: "Sudan",
    flag: "🇸🇩",
  },
  {
    dialCode: "+597",
    countryCode: "SR",
    name: "Suriname",
    flag: "🇸🇷",
  },
  {
    dialCode: "+47",
    countryCode: "SJ",
    name: "Svalbard and Jan Mayen",
    flag: "🇸🇯",
  },
  {
    dialCode: "+268",
    countryCode: "SZ",
    name: "Eswatini",
    flag: "🇸🇿",
  },
  {
    dialCode: "+46",
    countryCode: "SE",
    name: "Sweden",
    flag: "🇸🇪",
  },
  {
    dialCode: "+41",
    countryCode: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
  },
  {
    dialCode: "+963",
    countryCode: "SY",
    name: "Syria",
    flag: "🇸🇾",
  },
  {
    dialCode: "+886",
    countryCode: "TW",
    name: "Taiwan",
    flag: "🇹🇼",
  },
  {
    dialCode: "+992",
    countryCode: "TJ",
    name: "Tajikistan",
    flag: "🇹🇯",
  },
  {
    dialCode: "+255",
    countryCode: "TZ",
    name: "Tanzania",
    flag: "🇹🇿",
  },
  {
    dialCode: "+66",
    countryCode: "TH",
    name: "Thailand",
    flag: "🇹🇭",
  },
  {
    dialCode: "+228",
    countryCode: "TG",
    name: "Togo",
    flag: "🇹🇬",
  },
  {
    dialCode: "+690",
    countryCode: "TK",
    name: "Tokelau",
    flag: "🇹🇰",
  },
  {
    dialCode: "+676",
    countryCode: "TO",
    name: "Tonga",
    flag: "🇹🇴",
  },
  {
    dialCode: "+1 868",
    countryCode: "TT",
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
  },
  {
    dialCode: "+216",
    countryCode: "TN",
    name: "Tunisia",
    flag: "🇹🇳",
  },
  {
    dialCode: "+90",
    countryCode: "TR",
    name: "Turkey",
    flag: "🇹🇷",
  },
  {
    dialCode: "+993",
    countryCode: "TM",
    name: "Turkmenistan",
    flag: "🇹🇲",
  },
  {
    dialCode: "+1 649",
    countryCode: "TC",
    name: "Turks and Caicos Islands",
    flag: "🇹🇨",
  },
  {
    dialCode: "+688",
    countryCode: "TV",
    name: "Tuvalu",
    flag: "🇹🇻",
  },
  {
    dialCode: "+1 340",
    countryCode: "VI",
    name: "U.S. Virgin Islands",
    flag: "🇻🇮",
  },
  {
    dialCode: "+256",
    countryCode: "UG",
    name: "Uganda",
    flag: "🇺🇬",
  },
  {
    dialCode: "+380",
    countryCode: "UA",
    name: "Ukraine",
    flag: "🇺🇦",
  },
  {
    dialCode: "+971",
    countryCode: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
  },
  {
    dialCode: "+44",
    countryCode: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    dialCode: "+1",
    countryCode: "US",
    name: "United States",
    flag: "🇺🇸",
  },
  {
    dialCode: "+598",
    countryCode: "UY",
    name: "Uruguay",
    flag: "🇺🇾",
  },
  {
    dialCode: "+998",
    countryCode: "UZ",
    name: "Uzbekistan",
    flag: "🇺🇿",
  },
  {
    dialCode: "+678",
    countryCode: "VU",
    name: "Vanuatu",
    flag: "🇻🇺",
  },
  {
    dialCode: "+379",
    countryCode: "VA",
    name: "Vatican City",
    flag: "🇻🇦",
  },
  {
    dialCode: "+58",
    countryCode: "VE",
    name: "Venezuela",
    flag: "🇻🇪",
  },
  {
    dialCode: "+84",
    countryCode: "VN",
    name: "Vietnam",
    flag: "🇻🇳",
  },
  {
    dialCode: "+681",
    countryCode: "WF",
    name: "Wallis and Futuna",
    flag: "🇼🇫",
  },
  {
    dialCode: "+212",
    countryCode: "EH",
    name: "Western Sahara",
    flag: "🇪🇭",
  },
  {
    dialCode: "+967",
    countryCode: "YE",
    name: "Yemen",
    flag: "🇾🇪",
  },
  {
    dialCode: "+260",
    countryCode: "ZM",
    name: "Zambia",
    flag: "🇿🇲",
  },
  {
    dialCode: "+263",
    countryCode: "ZW",
    name: "Zimbabwe",
    flag: "🇿🇼",
  },
];
